Initial commit of this truncate filter.
logstash-plugins/logstash-filter-truncate pull request #1
Opened 2016-11-21 21:30 UTC by jordansissel

Purpose is to enable byte-length truncation of fields in Logstash.

2016-11-22 11:10 UTC, gmoskovicz commented
Sweet!

@jordansissel from the gemspec it looks like this is only going to be compatible with 2.4 and higher versions of Logstash right? Just to verify this :)

2016-11-22 16:20 UTC, jordansissel commented
@gmoskovicz Yes. My intended target is 5.x, but fortunately we have backported the plugin api for 5.0.0 to 2.4.x so this plugin should work on it.

2016-11-22 18:25 UTC, ph requested changes
Really minimal changes needed.

`Yay` for removing one common usage of the ruby filter.

2016-11-22 18:25 UTC, ph commented on lib/logstash/filters/truncate.rb
> +  config :fields, :validate => :string, :list => true
Maybe add a note about the behavior if the target field is a `hash/array`

2016-11-22 18:25 UTC, ph commented on lib/logstash/filters/truncate.rb
> +  end
Since `@length_bytes` is an instance variable we don't need to pass it as an argument

2016-11-22 18:25 UTC, ph commented on lib/logstash/filters/truncate.rb
> +  end
I am with you on this, I don't think there an easy way right now. :(

2016-11-22 18:25 UTC, ph commented on logstash-filter-truncate.gemspec
> +  s.version         = '0.0.1'
Any reason why we don't make it 1.0.0?

2016-11-22 18:25 UTC, ph commented on spec/filters/truncate_spec.rb
> +    #let(:length) { 5 }
removed commented lines?

2016-11-22 18:25 UTC, ph commented on spec/filters/truncate_spec.rb
> +    }
I've looked at Flores random text and it uses multibytes chars.

2016-11-22 18:25 UTC, ph commented on Gemfile
> +gem "flores", :path => "../ruby-flores"
Maybe remove this?

2016-11-22 18:25 UTC, ph commented on Gemfile
> +# Specify your gem's dependencies in logstash-mass_effect.gemspec
mass_effect? :)

2016-11-22 20:04 UTC, jordansissel commented on lib/logstash/filters/truncate.rb
> +  end
These probably belong as utility methods somewhere else. I'll make them be class methods instead.

2016-11-22 20:05 UTC, jordansissel commented on logstash-filter-truncate.gemspec
> +  s.version         = '0.0.1'
I try to start new projects at 0.0.1 as a practice.

I'm fine with 1.0.0, though, an dwill make that change.

2016-11-22 20:06 UTC, jordansissel commented on spec/filters/truncate_spec.rb
> +    }
Indeed! This is useful to help make sure we truncate to byte-length and then round down to the nearest utf-8 character.

2016-11-22 20:06 UTC, jordansissel commented on Gemfile
> +# Specify your gem's dependencies in logstash-mass_effect.gemspec
hah, copied from mutate filter, I think.

2016-11-22 20:07 UTC, jordansissel commented on Gemfile
> +gem "flores", :path => "../ruby-flores"
Yep, oops! I published flores 0.0.7 with the changes I needed.

2016-11-22 21:26 UTC, jordansissel commented
@ph changes made.

2016-11-23 14:01 UTC, ph approved these changes

2016-11-23 14:01 UTC, ph commented
LGTM

2016-11-29 00:37 UTC, closed without merging

2016-11-29 13:48 UTC, gmoskovicz commented
W00t

2016-11-29 20:45 UTC, jordansissel commented
```
% rake publish_gem
Published logstash-filter-truncate-1.0.0.gem
```